import express from 'express';
import fs from 'fs';
import path from 'path';

import resourceLibraryRoutes from './resourceLibraryRoutes.js';
import categoryRoutes from './categoryRoutes.js';
import authRoutes from './authRoutes.js';
import aiToolRoutes from './aiToolRoutes.js';
import nasaImageRoutes from './nasaImageRoutes.js';
import adminToolsRoutes from './adminToolsRoutes.js';
import youtubeChannelRoutes from './youtubeChannelRoutes.js';
import trainingResourceRoutes from './trainingResourceRoutes.js';
import shortCategoryRoutes from './shortCategoryRoutes.js';
import viralShortRoutes from './viralShortRoutes.js';
import gmailRoutes from './gmailRoutes.js';
import emailContextsRoutes from './emailContexts.js';
import scamPostRoutes from './scamPostRoutes.js';
import adminEmailEntryRoutes from './adminEmailEntryRoutes.js';
import adminEmailArticleRoutes from './adminEmailArticleRoutes.js';
import aiDetectorRoutes from './aiDetectorRoutes.js';
import uploadRoutes from './uploadRoutes.js';
import socialPostRoutes from './socialPostRoutes.js';
import animeCharacterRoutes from './animeCharacterRoutes.js';
import animePromptDataRoutes from './animePromptDataRoutes.js';
import animePromptRoutes from './animePromptRoutes.js';
import affiliateLinkRoutes from './affiliateLinkRoutes.js';
import affiliateClickRoutes from './affiliateClickRoutes.js';
import igraalDealRoutes from './igraalDealRoutes.js';
import igraalCouponRoutes from './igraalCouponRoutes.js';
import seriesRoutes from './seriesRoutes.js';
import seriesCategoryRoutes from './seriesCategoryRoutes.js';
import adminSuspiciousRoutes from './adminSuspiciousRoutes.js';
import rateLimitBlockRoutes from './rateLimitBlockRoutes.js';
import adminEnrichRoute from './adminEnrichRoute.js';
import spacexPublicRoutes from './spacexPublicRoutes.js';
import spacexAdminRoutes from './spacexAdminRoutes.js';
import linkAnalysisRoutes from './linkAnalysisRoutes.js';
import adminLinkAnalysisRoutes from './adminLinkAnalysisRoutes.js';
import proLinkAnalysisRoutes from './proLinkAnalysisRoutes.js';
import youtubeAuthRoutes from './youtubeAuthRoutes.js';
import youtubeUploadRoutes from './youtubeUploadRoutes.js';
import youtubeTokenRoutes from './youtubeTokenRoutes.js';
import userFavoriteSeriesRoutes from './userFavoriteSeriesRoutes.js';
import userSeriesStatsRoutes from './userSeriesStatsRoutes.js';
import favoriteRoutes from './favoriteRoutes.js';
import shareRoutes from './shareRoutes.js';
import promptPackRoutes from './promptPackRoutes.js';
import promptItemRoutes from './promptItemRoutes.js';
import promptOptionGroupRoutes from './promptOptionGroupRoutes.js';
import promptOptionRoutes from './promptOptionRoutes.js';
import userPromptFavoriteRoutes from './userPromptFavoriteRoutes.js';
import promptUsageLogRoutes from './promptUsageLogRoutes.js';
import legacyImportRoutes from './keikoImportRoutes.js';
import keikoPackRoutes from '../keikoprompts/routes/packs.js';
import keikoPromptRoutes from '../keikoprompts/routes/prompts.js';
import keikoOptionRoutes from '../keikoprompts/routes/options.js';
import keikoImportRoutes from '../keikoprompts/routes/import.js';
import duplicateRoutes from '../keikoprompts/routes/duplicateRoutes.js';
import motogpRoutes from './motogpRoutes.js';
import comfyRoutes from './comfyRoutes.js';
import fluxRoutes from './fluxRoutes.js';
import tokenRoutes from './tokenRoutes.js';
import imagenesPublicasRoutes from './imagenesPublicasRoutes.js';
import devTestRoutes from '../keikoprompts/routes/devTestRoutes.js';
import sportsRoutes from './sportsRoutes.js';
import imagenesRoutes from './imagenes.route.js';
import formula1Routes from './formula1Routes.js';
import keikoRemoveBGRoutes from './keikoRemoveBGRoutes.js';
import sportsEventsRoutes from './sportsEvents.routes.js';
import convertRoutes from './convertRoutes.js';
import compressRoutes from './compressRoutes.js';
import resizeRoutes from './resizeRoutes.js';
import watermarkRoutes from './watermarkRoutes.js';
import pixelateRoutes from './pixelateRoutes.js';
import cropRoutes from './cropRoutes.js';
import rotateRoutes from './rotateRoutes.js';
import capturaDesdeUrlRoutes from './capturaDesdeUrlRoutes.js';
import downloadRoutes from './downloadRoutes.js';
import zipRoutes from './zipRoutes.js';
import favoritoRoutes from './favoritoRoutes.js';
import eventsRoutes from './events.routes.js';
import futbolRoutes from './futbolRoutes.js';
import generadorIARoutes from './generadorIARoutes.js';
import cpxRoutes from './cpxRoutes.js';
import trackingRoutes from './trackingRoutes.js';
import text2imageRoutes from './text2imageRoutes.js';
import instagramRoutes from './instagramRoutes.js';
import blogRoutes from './blogRoutes.js';
import summaryRoutes from './telegram.js';
import f1Routes from './telegram-f1.js';
import upscaler from './keikoUpscaleRoutes.js';
import telegramRoutes from './telegram.routes.js';
import weeklyRoutes from './weeklyRoutes.js';
import filamentRoutes from './filamentRoutes.js';

export const registerApiRoutes = ({ app, __dirname, rebuildWeeklyForAccount }) => {
  app.use('/api/instagram', instagramRoutes);
  app.use('/api/generacion', text2imageRoutes);
  app.use('/api/tracking', trackingRoutes);
  app.use('/api', eventsRoutes);
  app.use('/api/favoritos', favoritoRoutes);
  app.use('/zip', zipRoutes);
  app.use('/api/download', downloadRoutes);
  app.use('/api', upscaler);
  app.use('/api/telegram', telegramRoutes);
  app.use('/api/resources', resourceLibraryRoutes);
  app.use('/api/anime-characters', animeCharacterRoutes);
  app.use('/api/auth', authRoutes);
  app.use('/api/categories', categoryRoutes);
  app.use('/api/aitools', aiToolRoutes);
  app.use('/api/nasa-images', nasaImageRoutes);
  app.use('/api/admin', adminToolsRoutes);
  app.use('/api/social-posts', socialPostRoutes);
  app.use('/api/youtube-channels', youtubeChannelRoutes);
  app.use('/api/training-resources', trainingResourceRoutes);
  app.use('/api/short-categories', shortCategoryRoutes);
  app.use('/api/viral-shorts', viralShortRoutes);
  app.use('/api/gmail', gmailRoutes);
  app.use('/api/admin/email-contexts', emailContextsRoutes);
  app.use('/api/scam-posts', scamPostRoutes);
  app.use('/api/admin/email-entries', adminEmailEntryRoutes);
  app.use('/api/admin/email-articles', adminEmailArticleRoutes);
  app.use('/api/ai', aiDetectorRoutes);
  app.use('/api/upload', uploadRoutes);
  app.use('/api/anime-prompt-data', animePromptDataRoutes);
  app.use('/api/anime-prompts', animePromptRoutes);
  app.use('/api/affiliate-links', affiliateLinkRoutes);
  app.use('/api/affiliate-clicks', affiliateClickRoutes);
  app.use('/api/igraal-deals', igraalDealRoutes);
  app.use('/api/igraal-coupons', igraalCouponRoutes);
  app.use('/api/series/categories', seriesCategoryRoutes);
  app.use('/api/series', seriesRoutes);
  app.use('/api/admin/suspicious-access', adminSuspiciousRoutes);
  app.use('/api/admin/rate-limit-blocks', rateLimitBlockRoutes);
  app.use('/api', adminEnrichRoute);
  app.use('/api/spacex', spacexPublicRoutes);
  app.use('/api/admin', spacexAdminRoutes);
  app.use('/api', linkAnalysisRoutes);
  app.use('/api/admin', adminLinkAnalysisRoutes);
  app.use('/api/pro', proLinkAnalysisRoutes);
  app.use('/api/youtube', youtubeAuthRoutes);
  app.use('/api/youtube', youtubeUploadRoutes);
  app.use('/api/youtube', youtubeTokenRoutes);
  app.use('/api/user/favorites', userFavoriteSeriesRoutes);
  app.use('/api', userSeriesStatsRoutes);
  app.use('/api/series/favorites', favoriteRoutes);
  app.use('/share', shareRoutes);
  app.use('/api/prompt-packs', promptPackRoutes);
  app.use('/api/prompt-items', promptItemRoutes);
  app.use('/api/option-groups', promptOptionGroupRoutes);
  app.use('/api/prompt-options', promptOptionRoutes);
  app.use('/api/favorites', userPromptFavoriteRoutes);
  app.use('/api/prompt-usage', promptUsageLogRoutes);
  app.use('/api/admin/keiko', legacyImportRoutes);
  app.use('/api/keiko/packs', keikoPackRoutes);
  app.use('/api/keiko/prompts', keikoPromptRoutes);
  app.use('/api/keiko/options', keikoOptionRoutes);
  app.use('/api/keiko/import', keikoImportRoutes);
  app.use('/api/keiko/duplicates', duplicateRoutes);
  app.use('/api/sports/motogp', motogpRoutes);
  app.use('/api/comfy', comfyRoutes);
  app.use('/api/tokens', tokenRoutes);
  app.use('/api/flux', fluxRoutes);
  app.use('/api/public-images', imagenesPublicasRoutes);
  app.use('/api/dev', devTestRoutes);
  app.use('/api/sports', sportsRoutes);
  app.use('/api/imagenes', imagenesRoutes);
  app.use('/api', formula1Routes);
  app.use('/api/keiko-remove-bg', keikoRemoveBGRoutes);
  app.use('/api/sports-events', sportsEventsRoutes);
  app.use('/api', convertRoutes);
  app.use('/api', compressRoutes);
  app.use('/api', resizeRoutes);
  app.use('/api', watermarkRoutes);
  app.use('/api', pixelateRoutes);
  app.use('/api', cropRoutes);
  app.use('/api', rotateRoutes);
  app.use('/api/captura-url', capturaDesdeUrlRoutes);
  app.use('/api/generador', generadorIARoutes);
  app.use('/api/recompensas', cpxRoutes);

  app.use('/cropped', express.static(path.join(__dirname, 'public/cropped')));
  app.use('/pixelated', express.static(path.join(__dirname, 'public/pixelated'), {
    setHeaders: (res) => {
      res.setHeader('Access-Control-Allow-Origin', '*');
    },
  }));

  app.get('/zip/:filename', (req, res) => {
    const filePath = path.join(__dirname, 'public', 'zip', req.params.filename);
    res.download(filePath, () => {
      fs.unlink(filePath, () => {});
    });
  });

  app.use('/api/blog', blogRoutes);
  app.use('/api/summaryRoutes', summaryRoutes);
  app.use('/api/telegram-f1', f1Routes);
  app.use('/api/futbol', futbolRoutes);
  app.use('/api/weekly', weeklyRoutes);
  app.use('/api/filaments', filamentRoutes);

  app.post('/api/weekly/rebuild/:accountId', async (req, res) => {
    try {
      await rebuildWeeklyForAccount(req.params.accountId);
      res.json({ ok: true });
    } catch (e) {
      res.status(500).json({ error: e.message || 'Error rebuild' });
    }
  });
};
